export const sliderItems = [
  {
    id: 1,
    img: "https://github.com/kowo0403hk/e-commerce-ts/blob/main/client/docs/Slider1.jpeg?raw=true",
    title: "Oink.",
    desc: "Be an owner this summer!",
    bg: "ffffff",
  },
  {
    id: 2,
    img: "https://github.com/kowo0403hk/e-commerce-ts/blob/main/client/docs/Slider2.jpeg?raw=true",
    title: "Own a double.",
    desc: "It is more fun to have more piggies.",
    bg: "fcf1ed",
  },
  {
    id: 3,
    img: "https://github.com/kowo0403hk/e-commerce-ts/blob/main/client/docs/Slider3.jpg?raw=true",
    title: "MINI!",
    desc: "Imagine a pig that never grows.",
    bg: "fbf0f4",
  },
];

export const categories = [
  {
    id: 1,
    img: "https://github.com/kowo0403hk/e-commerce-ts/blob/main/client/docs/Categories1.jpeg?raw=true",
    title: "PINK FEVER",
    cat: "Pearl",
  },
  {
    id: 2,
    img: "https://github.com/kowo0403hk/e-commerce-ts/blob/main/client/docs/Categories2.jpg?raw=true",
    title: "SPOTTED LOVE",
    cat: "Buchi",
  },
  {
    id: 3,
    img: "https://github.com/kowo0403hk/e-commerce-ts/blob/main/client/docs/Categories3.jpg?raw=true",
    title: "JUST STUFFY!",
    cat: "Stuffy",
  },
];

export const products = [
  {
    title: "Pearl #1",
    desc: "A special kind of piggy that you have to own in your life. They are tiny, kind, and can give you warmth. The have smooth and shiny fur. Give it a try!",
    img: "https://github.com/kowo0403hk/e-commerce-ts/blob/main/client/docs/pearl1.png?raw=true",
    categories: ["Pearl"],
    color: ["pink"],
    size: ["Mini", "Micro", "Medium"],
    price: 100000,
  },
  {
    title: "Pearl #2",
    desc: "A special kind of piggy that you have to own in your life. They are tiny, kind, and can give you warmth. The have smooth and shiny fur. Give it a try!",
    img: "https://github.com/kowo0403hk/e-commerce-ts/blob/main/client/docs/pearl2.jpeg?raw=true",
    categories: ["Pearl"],
    color: ["pink"],
    size: ["Mini", "Micro"],
    price: 120000,
  },
  {
    title: "Pearl #3",
    desc: "A special kind of piggy that you have to own in your life. They are tiny, kind, and can give you warmth. The have smooth and shiny fur. Give it a try!",
    img: "https://github.com/kowo0403hk/e-commerce-ts/blob/main/client/docs/pearl3.jpeg?raw=true",
    categories: ["Pearl"],
    color: ["pink"],
    size: ["Micro", "Medium"],
    price: 150000,
  },
  {
    title: "Buchi #1",
    desc: "The spotted piggy that can ignite your love towards pigs! Different from the pure pink pig, these types of pig has their own charm and you will fell in love with them a little bit more every single day!.",
    img: "https://github.com/kowo0403hk/e-commerce-ts/blob/main/client/docs/buchi1.jpeg?raw=true",
    categories: ["Buchi"],
    color: ["brown"],
    size: ["Mini", "Micro", "Medium"],
    price: 100000,
  },
  {
    title: "Buchi #2",
    desc: "The spotted piggy that can ignite your love towards pigs! Different from the pure pink pig, these types of pig has their own charm and you will fell in love with them a little bit more every single day!.",
    img: "https://github.com/kowo0403hk/e-commerce-ts/blob/main/client/docs/buchi2.jpeg?raw=true",
    categories: ["Buchi"],
    color: ["brown"],
    size: ["Micro", "Medium"],
    price: 120000,
  },
  {
    title: "Buchi #3",
    desc: "The spotted piggy that can ignite your love towards pigs! Different from the pure pink pig, these types of pig has their own charm and you will fell in love with them a little bit more every single day!.",
    img: "https://github.com/kowo0403hk/e-commerce-ts/blob/main/client/docs/buchi3.jpeg?raw=true",
    categories: ["Buchi"],
    color: ["brown"],
    size: ["Mini", "Micro", "Medium"],
    price: 150000,
  },
  {
    title: "Stuffy #1",
    desc: "Meet Goro! Although he is not a real piggy, but he can also keep you warm when you sleep. His fluffy fur will melt your heart instantly!",
    img: "https://github.com/kowo0403hk/e-commerce-ts/blob/main/client/docs/stuffy1.jpeg?raw=true",
    categories: ["Stuffy"],
    color: ["pink"],
    size: ["One size"],
    price: 3499,
  },
  {
    title: "Stuffy #2",
    desc: "Meet Goro! Although he is not a real piggy, but he can also keep you warm when you sleep. His fluffy fur will melt your heart instantly!",
    img: "https://raw.githubusercontent.com/kowo0403hk/e-commerce-ts/main/client/docs/stuffy2.webp",
    categories: ["Stuffy"],
    color: ["pink"],
    size: ["One size"],
    price: 3499,
  },
  {
    title: "Stuffy #3",
    desc: "Meet Goro! Although he is not a real piggy, but he can also keep you warm when you sleep. His fluffy fur will melt your heart instantly!",
    img: "https://github.com/kowo0403hk/e-commerce-ts/blob/main/client/docs/stuffy3.jpg?raw=true",
    categories: ["Stuffy"],
    color: ["pink"],
    size: ["One size"],
    price: 3499,
  },
];
